### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by gtcrea** [tretos53/Captive-Portal-WordPress#1]
It doesn't work for me with Raspberry pi3.
It does not create any wireless network.

**Comment by 23ewrdtf** [comment]
Hi,
My fault for not describing this project. There are a lot of problems with it and it doesn't work at the moment (wordpress part) so please use the original project. For your issue run hostapd /etc/hostapd/hostapd.conf and then check if it created wifi. If it did then the command to run hostapd at boot doesn't work (fixed now). If it didn't, make sure to set the country code as this is a requirement for wifi to work in the latest Raspberry pi3.

**Comment by gtcrea** [comment]
Thanks for the clarification, I needed something similar and with wordpress. Will you continue to develop this project in the future?

**Comment by 23ewrdtf** [comment]
Hi, Yes, possibly as I needed something similar. Just didn't have time. The issue with WP seems to be with a couple of things I think.
1. nginx security
2. iptables possibly
3. nginx config redirecting everything
4. other...

**Comment by 23ewrdtf** [comment]
Can you run below script please and test? 

Before you run please set the location country as it's required in the new PIs for wifi to work.

`sudo -i`

`curl -H 'Cache-Control: no-cache' -sSL https://raw.githubusercontent.com/tretos53/Captive-Portal-WordPress/master/captiveportal_wp.sh | sudo bash $0`
