### ISSUE TITLE
AP doesnt starts

### ISSUE THREAD

**Issue by bombardinotungtung** [tretos53/Captive-Portal-WordPress#2]
AP doesnt starts.tried to change wifi country.both before and after setup.tried buster and jessie.still ap doesnt shows up.

**Comment by 23ewrdtf** [comment]
I'll check this after 12th January when I'm back from leave.

**Comment by 23ewrdtf** [comment]
Check syslog for any errors.
Is hostapd service running after reboot ?
I think that's how you test the configuration (path may be wrong): sudo /usr/sbin/hostapd /etc/hostapd/hostapd.conf

**Comment by baritonerosecandytea** [comment]
my usb data port is broken so i cannot plug keyboard to it.i can only check via chrooting to sdcard.which log you want me to look at ?

**Comment by 23ewrdtf** [comment]
You can ssh into the pi and check, no need for usb keyboard.

The logs should be in /var/log/syslog
